apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod  # Replace with your ClusterIssuer name
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jaygala25@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio  # This tells cert-manager to use the Istio ingress
