apiVersion: v1
kind: Secret
metadata:
  name: medical-coding-secrets
type: Opaque
data:
  # --- Backend Variables ---
  BACKEND_USERNAME: Y29tbXVyZQ==
  BACKEND_PASSWORD: Y29kZXM=

  PINECONE_API_KEY: cGNzaytfMzFoRlh5X0V1ajJqNkRXYU5MYjRuTHo0dVB0aWFhY3NncEU0NWtKTVVZTmNFOXdzc2JMTXdKakpoVzlQZFF1dGo0VmFRcg==
  PINECONE_ENVIRONMENT: dXMtZWFzdC0xLWF3cw== # base64 encoded "us-east-1-aws"
  PINECONE_ICD_INDEX_NAME: aWNkLWNvZGVz # base64 encoded "icd-codes"
  PINECONE_CPT_INDEX_NAME: Y3B0LWNvZGVz # base64 encoded "cpt-codes"
  GOOGLE_PROJECT_ID: c2lsaWNvbi13b3Jrcy00NDk4MTctbjc= # base64 encoded "silicon-works-449817-n7"
  GOOGLE_LOCATION: dXMtY2VudHJhbDE= # base64 encoded "us-central1"
  VERTEX_MODEL_NAME: dGV4dC1lbWJlZGRpbmctMDA0 # base64 encoded "text-embedding-004"

  # --- Frontend Variables ---
  # BACKEND_API_URL is set differently in the frontend deployment (using service discovery)
  # BACKEND_USERNAME and BACKEND_PASSWORD are listed above (reused)
  FRONTEND_USERNAME: YWRtaW4=
  FRONTEND_PASSWORD: cGFzc3dvcmQ=
